remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-menus

title: [Rubens C. Toledo]
layout: listing
menus:
  header:
    title: Home
    weight: 1
description: [A short description of your site's purpose, [link](https://rubensctoledo.github.io/CV/p1)]
google_analytics: [Your Google Analytics tracking ID]

