remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Rubens C. Toledo]

description: [A short description of your site's purpose]
google_analytics: [Your Google Analytics tracking ID]

