remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-menus

title: [Rubens C. Toledo]
menus:
  header:
    title: Home
    weight: 1
description: [A short description of your site's purpose]
google_analytics: [Your Google Analytics tracking ID]

