remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Rubens C. Toledo]
description: [A short description of your site's purpose]
google_analytics: [Your Google Analytics tracking ID]



# Build settings
markdown: kramdown

collections:
  episodes:
    output: true
  seasons:
    output: true
  characters:
    output: true

defaults:
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: "episode"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"
  - scope:
      path: ""
      type: "seasons"
    values:
      layout: "season"
gems:
  - octopress-paginate

