remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Rubens C. Toledo]

description: [A short description of your site's purpose, [link](https://rubensctoledo.github.io/CV/p1)]
google_analytics: [Your Google Analytics tracking ID]

